//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("onSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Net;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Threading.Tasks;
        ///
        ///namespace onSoft
        ///{
        ///    public class onHttpBase
        ///    {
        ///        protected readonly CookieContainer CookieJar = new CookieContainer();
        ///
        ///
        ///        protected Dictionary&lt;string, string&gt; GetDomControlElements(string html, List&lt;string&gt; inputElements)
        ///        {
        ///            var output = new Dictionary&lt;string, string&gt;();
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTemplate {
            get {
                return ResourceManager.GetString("BaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using RestSharp;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Net;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace onSoft
        ///{
        ///    public class GetTemplate: onHttpBase
        ///    {
        ///        public Dictionary&lt;string, string&gt; DomControls = new Dictionary&lt;string, string&gt;();
        ///        public void RunAll()
        ///        {
        ///            //RunGET11();
        ///        }
        ///
        ///        private IRestResponse Execute(string url)
        ///        {
        ///            var client = new RestClient(url);
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTemplate {
            get {
                return ResourceManager.GetString("GetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using RestSharp;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Net;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace onSoft
        ///{
        ///    public class PostTemplate: onHttpBase
        ///    {
        ///        public Dictionary&lt;string, string&gt; DomControls = new Dictionary&lt;string, string&gt;();
        ///        //{Body}
        ///        //Use https://app.quicktype.io/ to convert the body above into C# class then strongly type the postObject below
        ///        private IRestResponse Execute(string url, o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostTemplate {
            get {
                return ResourceManager.GetString("PostTemplate", resourceCulture);
            }
        }
    }
}
